### ISSUE TITLE
Map Screen Capture

### ISSUE THREAD

**Issue by gabriellataekema** [TraceyLauriault/COMS2200A#24]
I am in overpass to take a screencapture of my images and only 17 of my images are showing up, did OSM delete 3 of them or am I just not finding them? I uploaded them on time  so they should be on OSM.

**Comment by DenisCarriere** [comment]
This is a duplicate of another GitHub issue, please review this https://github.com/TraceyLauriault/COMS2200A/issues/27#issuecomment-336748398 made.

As long as you've got a minimum of 20 edits on OSM then you're 100% 👍 for that part of the assignment.
